import { SchoolProfile, Teacher, SchoolPeriod } from "@/types/school";

export const DEFAULT_SCHOOL_PROFILE: SchoolProfile = {
  className: "8G",
  shift: "Schimbul II",
  schoolYear: "2026–2027",
  homeroomTeacher: "Bicosu Ilona",
};

export const TEACHERS_DATABASE: Record<string, string> = {
  "Limba Română": "Dăianu Gabriela",
  "Română": "Dăianu Gabriela",
  "Limba Engleză": "Bicosu Ilona",
  "Engleză": "Bicosu Ilona",
  "Limba Franceză": "Dumbravă Nicoleta",
  "Franceză": "Dumbravă Nicoleta",
  "Matematică": "Voiasciuc Oana",
  "Mate": "Voiasciuc Oana",
  "Fizică": "Șofletea Aurelia",
  "Biologie": "Alexandru Dorina",
  "Chimie": "Stancu Ancuța Romina",
  "Istorie": "Gheorghe Camelia",
  "Geografie": "Peltecu Nicoleta",
  "Religie": "Bogdan Marinel",
  "Desen": "Iliescu Mihaela",
  "Muzică": "Mănăilescu Sorana",
  "Educație Financiară": "Țugui Maria",
  "Ed. Financiară": "Țugui Maria",
  "Tehnologie": "Gheorghiță Cristian",
  "TIC": "Chimet Adriana",
  "Sport": "Alăzăroaie Steliana",
  "Dirigenție": "Bicosu Ilona",
};

export const TEACHERS_LIST: Teacher[] = [
  { subject: "Limba Română", name: "Dăianu Gabriela" },
  { subject: "Limba Engleză", name: "Bicosu Ilona" },
  { subject: "Limba Franceză", name: "Dumbravă Nicoleta" },
  { subject: "Matematică", name: "Voiasciuc Oana" },
  { subject: "Fizică", name: "Șofletea Aurelia" },
  { subject: "Biologie", name: "Alexandru Dorina" },
  { subject: "Chimie", name: "Stancu Ancuța Romina" },
  { subject: "Istorie", name: "Gheorghe Camelia" },
  { subject: "Geografie", name: "Peltecu Nicoleta" },
  { subject: "Religie", name: "Bogdan Marinel" },
  { subject: "Desen", name: "Iliescu Mihaela" },
  { subject: "Muzică", name: "Mănăilescu Sorana" },
  { subject: "Educație Financiară", name: "Țugui Maria" },
  { subject: "Tehnologie", name: "Gheorghiță Cristian" },
  { subject: "TIC", name: "Chimet Adriana" },
  { subject: "Sport", name: "Alăzăroaie Steliana" },
  { subject: "Dirigenție", name: "Bicosu Ilona" },
];

export const DEFAULT_8G_SCHEDULE: SchoolPeriod[] = [
  // Luni
  {
    id: "luni-1",
    day: "Luni",
    startTime: "12:30",
    endTime: "13:20",
    subject: "Engleză",
    fullSubject: "Limba Engleză",
    teacher: "Bicosu Ilona",
  },
  {
    id: "luni-2",
    day: "Luni",
    startTime: "13:30",
    endTime: "14:20",
    subject: "Engleză",
    fullSubject: "Limba Engleză",
    teacher: "Bicosu Ilona",
  },
  {
    id: "luni-3",
    day: "Luni",
    startTime: "14:30",
    endTime: "15:20",
    subject: "Fizică",
    fullSubject: "Fizică",
    teacher: "Șofletea Aurelia",
  },
  {
    id: "luni-4",
    day: "Luni",
    startTime: "15:30",
    endTime: "16:20",
    subject: "Sport",
    fullSubject: "Educație Fizică și Sport",
    teacher: "Alăzăroaie Steliana",
  },
  {
    id: "luni-5",
    day: "Luni",
    startTime: "16:30",
    endTime: "17:20",
    subject: "Chimie",
    fullSubject: "Chimie",
    teacher: "Stancu Ancuța Romina",
  },
  {
    id: "luni-6",
    day: "Luni",
    startTime: "17:30",
    endTime: "18:20",
    subject: "Istorie",
    fullSubject: "Istorie",
    teacher: "Gheorghe Camelia",
  },

  // Marți
  {
    id: "marti-1",
    day: "Marți",
    startTime: "12:30",
    endTime: "13:20",
    subject: "Istorie",
    fullSubject: "Istorie",
    teacher: "Gheorghe Camelia",
  },
  {
    id: "marti-2",
    day: "Marți",
    startTime: "13:30",
    endTime: "14:20",
    subject: "Mate",
    fullSubject: "Matematică",
    teacher: "Voiasciuc Oana",
  },
  {
    id: "marti-3",
    day: "Marți",
    startTime: "14:30",
    endTime: "15:20",
    subject: "Geografie",
    fullSubject: "Geografie",
    teacher: "Peltecu Nicoleta",
  },
  {
    id: "marti-4",
    day: "Marți",
    startTime: "15:30",
    endTime: "16:20",
    subject: "Sport",
    fullSubject: "Educație Fizică și Sport",
    teacher: "Alăzăroaie Steliana",
  },
  {
    id: "marti-5",
    day: "Marți",
    startTime: "16:30",
    endTime: "17:20",
    subject: "Română",
    fullSubject: "Limba Română",
    teacher: "Dăianu Gabriela",
  },
  {
    id: "marti-6",
    day: "Marți",
    startTime: "17:30",
    endTime: "18:20",
    subject: "TIC",
    fullSubject: "Tehnologia Informației și a Comunicațiilor",
    teacher: "Chimet Adriana",
  },
  {
    id: "marti-7",
    day: "Marți",
    startTime: "18:25",
    endTime: "19:15",
    subject: "Religie",
    fullSubject: "Religie",
    teacher: "Bogdan Marinel",
  },

  // Miercuri
  {
    id: "miercuri-1",
    day: "Miercuri",
    startTime: "12:30",
    endTime: "13:20",
    subject: "Fizică",
    fullSubject: "Fizică",
    teacher: "Șofletea Aurelia",
  },
  {
    id: "miercuri-2",
    day: "Miercuri",
    startTime: "13:30",
    endTime: "14:20",
    subject: "Engleză",
    fullSubject: "Limba Engleză",
    teacher: "Bicosu Ilona",
  },
  {
    id: "miercuri-3",
    day: "Miercuri",
    startTime: "14:30",
    endTime: "15:20",
    subject: "Engleză",
    fullSubject: "Limba Engleză",
    teacher: "Bicosu Ilona",
  },
  {
    id: "miercuri-4",
    day: "Miercuri",
    startTime: "15:30",
    endTime: "16:20",
    subject: "Mate",
    fullSubject: "Matematică",
    teacher: "Voiasciuc Oana",
  },
  {
    id: "miercuri-5",
    day: "Miercuri",
    startTime: "16:30",
    endTime: "17:20",
    subject: "Română",
    fullSubject: "Limba Română",
    teacher: "Dăianu Gabriela",
  },
  {
    id: "miercuri-6",
    day: "Miercuri",
    startTime: "17:30",
    endTime: "18:20",
    subject: "Franceză",
    fullSubject: "Limba Franceză",
    teacher: "Dumbravă Nicoleta",
  },

  // Joi
  {
    id: "joi-1",
    day: "Joi",
    startTime: "12:30",
    endTime: "13:20",
    subject: "Ed. Financiară",
    fullSubject: "Educație Financiară",
    teacher: "Țugui Maria",
  },
  {
    id: "joi-2",
    day: "Joi",
    startTime: "13:30",
    endTime: "14:20",
    subject: "Franceză",
    fullSubject: "Limba Franceză",
    teacher: "Dumbravă Nicoleta",
  },
  {
    id: "joi-3",
    day: "Joi",
    startTime: "14:30",
    endTime: "15:20",
    subject: "Geografie",
    fullSubject: "Geografie",
    teacher: "Peltecu Nicoleta",
  },
  {
    id: "joi-4",
    day: "Joi",
    startTime: "15:30",
    endTime: "16:20",
    subject: "Mate",
    fullSubject: "Matematică",
    teacher: "Voiasciuc Oana",
  },
  {
    id: "joi-5",
    day: "Joi",
    startTime: "16:30",
    endTime: "17:20",
    subject: "Română",
    fullSubject: "Limba Română",
    teacher: "Dăianu Gabriela",
  },
  {
    id: "joi-6",
    day: "Joi",
    startTime: "17:30",
    endTime: "18:20",
    subject: "Chimie",
    fullSubject: "Chimie",
    teacher: "Stancu Ancuța Romina",
  },
  {
    id: "joi-7",
    day: "Joi",
    startTime: "18:25",
    endTime: "19:15",
    subject: "Tehnologie",
    fullSubject: "Educație Tehnologică",
    teacher: "Gheorghiță Cristian",
  },

  // Vineri
  {
    id: "vineri-1",
    day: "Vineri",
    startTime: "12:30",
    endTime: "13:20",
    subject: "Desen",
    fullSubject: "Educație Plastică (Desen)",
    teacher: "Iliescu Mihaela",
  },
  {
    id: "vineri-2",
    day: "Vineri",
    startTime: "13:30",
    endTime: "14:20",
    subject: "Română",
    fullSubject: "Limba Română",
    teacher: "Dăianu Gabriela",
  },
  {
    id: "vineri-3",
    day: "Vineri",
    startTime: "14:30",
    endTime: "15:20",
    subject: "Biologie",
    fullSubject: "Biologie",
    teacher: "Alexandru Dorina",
  },
  {
    id: "vineri-4",
    day: "Vineri",
    startTime: "15:30",
    endTime: "16:20",
    subject: "Mate",
    fullSubject: "Matematică",
    teacher: "Voiasciuc Oana",
  },
  {
    id: "vineri-5",
    day: "Vineri",
    startTime: "16:30",
    endTime: "17:20",
    subject: "Muzică",
    fullSubject: "Educație Muzicală",
    teacher: "Mănăilescu Sorana",
  },
  {
    id: "vineri-6",
    day: "Vineri",
    startTime: "17:30",
    endTime: "18:20",
    subject: "Dirigenție",
    fullSubject: "Consiliere și Dirigenție",
    teacher: "Bicosu Ilona",
  },
];
